# Decap CMS Configuration for Lake County Outdoors
backend:
  name: github
  repo: bgross0/lco-astro
  branch: main
  base_url: https://lakecountyoutdoor.com
  auth_endpoint: api/auth

# Media files storage
media_folder: "public/images/uploads" # Media files will be stored here
public_folder: "/images/uploads" # Public URL path

# Site URL for preview
site_url: https://lakecountyoutdoor.com
display_url: https://lakecountyoutdoor.com

# CMS configuration
# publish_mode: editorial_workflow  # Disabled to enable image uploads
logo_url: /lco-final.png

# Collections
collections:
  # Services Collection
  - name: "services"
    label: "Services"
    label_singular: "Service"
    folder: "src/content/services"
    create: true
    delete: true
    extension: "md"
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "text", required: true }
      - { label: "Featured Image", name: "image", widget: "image", required: true }
      - { label: "Display Order", name: "order", widget: "number", required: false, default: 0, hint: "Lower numbers appear first" }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  # Testimonials Collection
  - name: "testimonials"
    label: "Testimonials"
    label_singular: "Testimonial"
    folder: "src/content/testimonials"
    create: true
    delete: true
    extension: "md"
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Author", name: "author", widget: "string", required: true }
      - { label: "Company", name: "company", widget: "string", required: false }
      - { label: "Service", name: "service", widget: "string", required: true, hint: "Which service is this testimonial for?" }
      - { label: "Rating", name: "rating", widget: "number", min: 1, max: 5, default: 5, required: true }
      - { label: "Testimonial", name: "body", widget: "markdown", required: true }

  # Blog/News Posts (optional)
  - name: "blog"
    label: "Blog Posts"
    label_singular: "Blog Post"
    folder: "src/content/blog"
    create: true
    delete: true
    extension: "md"
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "text", required: true }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", required: true }
      - { label: "Author", name: "author", widget: "string", default: "Lake County Outdoors", required: true }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Image Alt Text", name: "imageAlt", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown", required: true }

  # Homepage Components (for editing homepage sections)
  - name: "homepage"
    label: "Homepage"
    label_singular: "Section"
    files:
      - label: "Hero Section"
        name: "hero"
        file: "src/content/homepage/hero.json"
        extension: "json"
        format: "json"
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
          - { label: "Description", name: "description", widget: "text", required: true }
          - { label: "CTA Text", name: "ctaText", widget: "string", default: "Get a Free Quote" }
          - { label: "CTA Link", name: "ctaLink", widget: "string", default: "/contact" }
      
      - label: "All Content Sections"
        name: "content"
        file: "src/content/homepage/content.json"
        extension: "json"
        format: "json"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            collapsed: true
            fields:
              - label: "Images"
                name: "images"
                widget: "list"
                fields:
                  - { label: "Image", name: "src", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string" }
          
          - label: "About Section"
            name: "about"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - label: "Paragraphs"
                name: "paragraphs"
                widget: "list"
                field: { label: "Paragraph", name: "paragraph", widget: "text" }
              - label: "Images"
                name: "images"
                widget: "list"
                fields:
                  - { label: "Image", name: "src", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string" }
              - label: "Features"
                name: "features"
                widget: "list"
                fields:
                  - { label: "Icon", name: "icon", widget: "string" }
                  - { label: "Text", name: "text", widget: "string" }
          
          - label: "Client Satisfaction"
            name: "clientSatisfaction"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - label: "Paragraphs"
                name: "paragraphs"
                widget: "list"
                field: { label: "Paragraph", name: "paragraph", widget: "text" }
              - { label: "Experience Title", name: "experienceTitle", widget: "string" }
              - { label: "Experience Text", name: "experienceText", widget: "text" }
              - { label: "Highlight", name: "highlight", widget: "text" }
          
          - label: "Equipment"
            name: "equipment"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - label: "Stats"
                name: "stats"
                widget: "list"
                fields:
                  - { label: "Number", name: "number", widget: "number" }
                  - { label: "Label", name: "label", widget: "string" }
          
          - label: "CTA Section"
            name: "cta"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Background Image", name: "backgroundImage", widget: "image" }
              - label: "Primary Button"
                name: "primaryButton"
                widget: "object"
                fields:
                  - { label: "Text", name: "text", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
              - label: "Secondary Button"
                name: "secondaryButton"
                widget: "object"
                fields:
                  - { label: "Text", name: "text", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }

  # Site Settings (optional)
  - name: "settings"
    label: "Settings"
    delete: false
    editor:
      preview: false
    files:
      - label: "General Settings"
        name: "general"
        file: "src/data/settings.json"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string" }
          - { label: "Site Description", name: "site_description", widget: "text" }
          - { label: "Logo", name: "logo", widget: "image", required: true }
          - { label: "OG Image (Social Share)", name: "og_image", widget: "image", required: false }
          - { label: "Phone Number", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Address", name: "address", widget: "text" }
          - { label: "Hours", name: "hours", widget: "string" }
          - label: "Social Media"
            name: "social"
            widget: "object"
            fields:
              - { label: "Facebook URL", name: "facebook", widget: "string", required: false }
              - { label: "Instagram URL", name: "instagram", widget: "string", required: false }
              - { label: "LinkedIn URL", name: "linkedin", widget: "string", required: false }
      
      - label: "Navigation"
        name: "navigation"
        file: "src/content/homepage/navigation.json"
        fields:
          - label: "Main Menu"
            name: "mainMenu"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Link", name: "href", widget: "string" }
              - { label: "Order", name: "order", widget: "number" }
          - label: "Footer Links"
            name: "footerLinks"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Link", name: "href", widget: "string" }
      
      - label: "Contact Page"
        name: "contact"
        file: "src/content/pages/contact.json"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
          - label: "Form Settings"
            name: "form"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Subtitle", name: "subtitle", widget: "string" }
              - { label: "Submit Button Text", name: "submitButtonText", widget: "string" }
          - label: "Contact Info"
            name: "info"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Emergency Text", name: "emergencyText", widget: "string" }
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - { label: "Page Title", name: "title", widget: "string" }
              - { label: "Meta Description", name: "description", widget: "text" }
